In [9]:
import numpy as np

In [10]:
n=np.array([[1,2,2],[3,56,78],[45,56,66]])

In [11]:
print(n)

[[ 1  2  2]
 [ 3 56 78]
 [45 56 66]]


In [12]:
n[1,:2]

array([ 3, 56])

# arange

In [16]:
list(range(4,54))

[4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53]

In [17]:
np.arange(4,54)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53])

In [18]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

# Reshape

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
a=np.arange(12).reshape(2,6)

In [23]:
np.sqrt(45)

6.708203932499369

In [26]:
a.max()

11

In [27]:
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [28]:
a.min()

0

In [29]:
n.argmax()

5

In [30]:
n.argmin()

0

In [31]:
n+10

array([[11, 12, 12],
       [13, 66, 88],
       [55, 66, 76]])

In [32]:
n*2

array([[  2,   4,   4],
       [  6, 112, 156],
       [ 90, 112, 132]])

# Random

In [33]:
np.random.rand(2,2)

array([[0.86925862, 0.78141089],
       [0.77494646, 0.07099109]])

In [34]:
np.random.rand(2)

array([0.45537862, 0.44699476])

In [36]:
np.random.randn(5,5)

array([[-2.93689007,  0.76615049,  0.46725475,  1.84965092, -2.20447154],
       [ 1.76687297, -0.16216227, -0.22394192,  0.18524039,  2.06821499],
       [-0.35145913,  1.48086052, -0.39918307, -0.02075912,  0.07075856],
       [-0.83929038,  0.35193648, -0.68977119,  0.25577325,  0.59905145],
       [-0.09395264, -0.35674004, -2.31081765,  0.54376386, -0.27585854]])

In [38]:
np.random.randint(9,90,14)

array([70, 23, 51, 59, 89, 16, 15, 89, 74, 66, 77, 58, 30, 33])

In [42]:
s=np.random.randint(9,90,14).reshape(7,2)

In [43]:
print(s)

[[86 49]
 [43 63]
 [88 44]
 [79 21]
 [66 55]
 [18 68]
 [66 55]]


In [44]:
s.sum()

801

In [45]:
s.sum(axis=1)

array([135, 106, 132, 100, 121,  86, 121])

In [46]:
s.sum(axis=0)

array([446, 355])