In [1]:
# Numeric Python
#pip install numpy

In [2]:
import numpy as np

In [3]:
a=np.array([])
b=np.array([1,2,3,4,5])
c=np.array([[122,42,4324],[234,232,322]])

In [4]:
a

array([], dtype=float64)

In [5]:
b

array([1, 2, 3, 4, 5])

In [6]:
c

array([[ 122,   42, 4324],
       [ 234,  232,  322]])

In [7]:
a

array([], dtype=float64)

In [8]:
type(a)

numpy.ndarray

In [9]:
c

array([[ 122,   42, 4324],
       [ 234,  232,  322]])

In [10]:
type(c)

numpy.ndarray

In [11]:
c.ndim

2

In [12]:
b.ndim

1

In [14]:
a.ndim

1

In [15]:
a.size

0

In [17]:
c.shape

(2, 3)

In [19]:
n=np.array([  [2,8,9,7]       ,        [456,587,5855,845]   ,     [3544,4534,534,34] ])

In [20]:
n.shape

(3, 4)

In [21]:
print(n)

[[   2    8    9    7]
 [ 456  587 5855  845]
 [3544 4534  534   34]]
